### ISSUE TITLE
radiusd crashes on a startup

### ISSUE THREAD

**Issue by ghost** [evansgp/docker-radius-eap-tls#1]
Hello

radiusd crashes on startup with errors in logs:

```
# Loading authenticate {...}
/etc/raddb/sites-enabled/site[35]: Failed to find "eap" as a module or policy.
/etc/raddb/sites-enabled/site[35]: Please verify that the configuration exists in /etc/raddb/mods-enabled/eap.
/etc/raddb/sites-enabled/site[34]: Errors parsing authenticate section. 

```
probably the problem lies here
COPY eap /etc/raddb/**modules-available**
but Radius is looking for module inside **mods-enabled** dir

Actualy I tried to replace modules-available to mods-enabled in the COPY instruction inside Dockerfile 
then rebuild docker image

but this time I ve got this:
```
 # Creating Auth-Type = eap
radiusd: #### Instantiating modules ####
 modules {
/etc/raddb/mods-enabled/eap[1]: Failed to link to module 'rlm_eap': Error loading shared library /usr/lib/freeradius/rlm_eap.so: No such file or directory 
```

It seems like the freeradius package had been changed a lot since you maintained the project

**Comment by viroel** [comment]
You shall fix this issue by installing freeradius-eap pkg:

`RUN apk add --no-cache freeradius freeradius-eap openssl`

**Comment by ghost** [comment]
sorry didn't notice your reply for years :)
I even don't remember what was the problem and the task

am closing the issue
Thanks
